=== wilfalken/nathmorvan/donnees/dtd/articles.dtd
<!ELEMENT barre_menu (menu*)>
<!ELEMENT menu (article*)>
      <!ATTLIST menu
      	nom_menu CDATA #REQUIRED
      	>
<!ELEMENT article (nom, element*)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT element (#PCDATA)>
      <!ATTLIST element
      	balise CDATA #REQUIRED
      	>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-03-02_22-09-04.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="Accueil">
    <article>
      <nom>Accueil</nom>
      <element balise="Image">crayons.jpg</element>
      <element balise="Paragraphe">Exsistit autem hoc loco quaedam quaestio subdifficilis, num quando amici novi, digni amicitia, veteribus sint anteponendi, ut equis vetulis teneros anteponere solemus. Indigna homine dubitatio! Non enim debent esse amicitiarum sicut aliarum rerum satietates; veterrima quaeque, ut ea vina, quae vetustatem ferunt, esse debet suavissima; verumque illud est, quod dicitur, multos modios salis simul edendos esse, ut amicitiae munus expletum sit.</element>
      <element balise="Paragraphe">Eodem tempore etiam Hymetii praeclarae indolis viri negotium est actitatum, cuius hunc novimus esse textum. cum Africam pro consule regeret Carthaginiensibus victus inopia iam lassatis, ex horreis Romano populo destinatis frumentum dedit, pauloque postea cum provenisset segetum copia, integre sine ulla restituit mora.</element>
      <element balise="Paragraphe">Nisi mihi Phaedrum, inquam, tu mentitum aut Zenonem putas, quorum utrumque audivi, cum mihi nihil sane praeter sedulitatem probarent, omnes mihi Epicuri sententiae satis notae sunt. atque eos, quos nominavi, cum Attico nostro frequenter audivi, cum miraretur ille quidem utrumque, Phaedrum autem etiam amaret, cotidieque inter nos ea, quae audiebamus, conferebamus, neque erat umquam controversia, quid ego intellegerem, sed quid probarem.</element>
    </article>
  </menu>
  <menu nom_menu="Présentation de l'école">
    <article>
      <nom>Classe passerelle</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Petite section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Moyenne section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Grande section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Cantine</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Horaires et emplois du temps">
    <article>
      <nom>Horaires et emplois du temps</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Inscriptions">
    <article>
      <nom>Inscriptions</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Conseils d'école">
    <article>
      <nom>2015</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>2016</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>2017</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>Archives</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
  </menu>
  <menu nom_menu="Contact">
    <article>
      <nom>Contact</nom>
      <element balise="Lien">http://www.google.com</element>
    </article>
  </menu>
</barre_menu>
