=== wilfalken/nathmorvan/donnees/dtd/articles.dtd
<!ELEMENT barre_menu (menu*)>
<!ELEMENT menu (article*)>
      <!ATTLIST menu
      	nom_menu CDATA #REQUIRED
      	>
<!ELEMENT article (nom, element*)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT element (#PCDATA)>
      <!ATTLIST element
      	balise CDATA #REQUIRED
      	>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-02-14_17-32-49.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu/>
  <menu nom_menu="La vie à l'école">
    <article>
      <nom>Présentation des classes</nom>
    </article>
    <article>
      <nom>Programme des classes</nom>
    </article>
    <article>
      <nom>Emploi du temps</nom>
    </article>
    <article>
      <nom>Présentation d'activités</nom>
    </article>
    <article>
      <nom>Matériel à disposition</nom>
    </article>
  </menu>
  <menu nom_menu="Etablissement">
    <article>
      <nom>Description</nom>
    </article>
    <article>
      <nom>Horaires</nom>
    </article>
    <article>
      <nom>Le menu de la cantine</nom>
    </article>
    <article>
      <nom>Classe passerelle</nom>
    </article>
    <article>
      <nom>Conseils d'école</nom>
      <element balise="Lien">../donnees/pdf/conseil.pdf</element>
    </article>
  </menu>
  <menu nom_menu="Inscription">
    <article>
      <nom>Conditions d'inscription</nom>
    </article>
    <article>
      <nom>Réglement intérieur</nom>
    </article>
  </menu>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-03-12_17-04-06.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="0">
    <article>
      <nom></nom>
    </article>
    <article>
      <nom></nom>
    </article>
  </menu>
  <menu nom_menu="1">
    <article>
      <nom>Présentation de l'école</nom>
    </article>
    <article>
      <nom></nom>
    </article>
  </menu>
  <menu nom_menu="2">
    <article>
      <nom>Horaires et emplois du temps</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom></nom>
    </article>
  </menu>
  <menu nom_menu="3">
    <article>
      <nom>Inscriptions</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom></nom>
    </article>
  </menu>
  <menu nom_menu="4">
    <article>
      <nom>Conseils d'école</nom>
    </article>
    <article>
      <nom></nom>
    </article>
  </menu>
  <menu nom_menu="5">
    <article>
      <nom>Contact</nom>
      <element balise="Lien">http://www.google.com</element>
    </article>
    <article>
      <nom></nom>
    </article>
  </menu>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-03-12_17-56-29.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="">
    <article>
      <nom>Accueil</nom>
    </article>
    <article>
      <nom></nom>
      <element balise="Paragraphe">hujdsfshjoiezfhiopfuoreupoier</element>
      <element balise="Sous-titre">titre</element>
      <element balise="Paragraphe">iopuoireujrortio</element>
      <element balise="Image">_image_defaut.jpg</element>
      <element balise="Sous-titre">Carrousel</element>
      <element balise="Paragraphe">Eodem tempore etiam Hymetii praeclarae indolis viri negotium est actitatum, cuius hunc novimus esse textum. cum Africam pro consule regeret Carthaginiensibus victus inopia iam lassatis, ex horreis Romano populo destinatis frumentum dedit, pauloque postea cum provenisset segetum copia, integre sine ulla restituit mora.</element>
      <element balise="Paragraphe">Nec sane haec sola pernicies orientem diversis cladibus adfligebat. Namque et Isauri, quibus est usitatum saepe pacari saepeque inopinis excursibus cuncta miscere, ex latrociniis occultis et raris, alente inpunitate adulescentem in peius audaciam ad bella gravia proruperunt, diu quidem perduelles spiritus inrequietis motibus erigentes, hac tamen indignitate perciti vehementer, ut iactitabant, quod eorum capiti quidam consortes apud Iconium Pisidiae oppidum in amphitheatrali spectaculo feris praedatricibus obiecti sunt praeter morem.</element>
      <element balise="Paragraphe">Nisi mihi Phaedrum, inquam, tu mentitum aut Zenonem putas, quorum utrumque audivi, cum mihi nihil sane praeter sedulitatem probarent, omnes mihi Epicuri sententiae satis notae sunt. atque eos, quos nominavi, cum Attico nostro frequenter audivi, cum miraretur ille quidem utrumque, Phaedrum autem etiam amaret, cotidieque inter nos ea, quae audiebamus, conferebamus, neque erat umquam controversia, quid ego intellegerem, sed quid probarem.</element>
      <element balise="Paragraphe">Vbi curarum abiectis ponderibus aliis tamquam nodum et codicem difficillimum Caesarem convellere nisu valido cogitabat, eique deliberanti cum proximis clandestinis conloquiis et nocturnis qua vi, quibusve commentis id fieret, antequam effundendis rebus pertinacius incumberet confidentia, acciri mollioribus scriptis per simulationem tractatus publici nimis urgentis eundem placuerat Gallum, ut auxilio destitutus sine ullo interiret obstaculo.</element>
      <element balise="Paragraphe">Postremo ad id indignitatis est ventum, ut cum peregrini ob formidatam haut ita dudum alimentorum inopiam pellerentur ab urbe praecipites, sectatoribus disciplinarum liberalium inpendio paucis sine respiratione ulla extrusis, tenerentur minimarum adseclae veri, quique id simularunt ad tempus, et tria milia saltatricum ne interpellata quidem cum choris totidemque remanerent magistris.</element>
      <element balise="Sous-titre">Olim</element>
      <element balise="Paragraphe">Et olim licet otiosae sint tribus pacataeque centuriae et nulla suffragiorum certamina set Pompiliani redierit securitas temporis, per omnes tamen quotquot sunt partes terrarum, ut domina suscipitur et regina et ubique patrum reverenda cum auctoritate canities populique Romani nomen circumspectum et verecundum.</element>
      <element balise="Paragraphe">Quanta autem vis amicitiae sit, ex hoc intellegi maxime potest, quod ex infinita societate generis humani, quam conciliavit ipsa natura, ita contracta res est et adducta in angustum ut omnis caritas aut inter duos aut inter paucos iungeretur.</element>
      <element balise="Paragraphe">Primi igitur omnium statuuntur Epigonus et Eusebius ob nominum gentilitatem oppressi. praediximus enim Montium sub ipso vivendi termino his vocabulis appellatos fabricarum culpasse tribunos ut adminicula futurae molitioni pollicitos.</element>
    </article>
  </menu>
  <menu nom_menu="Présentation de l'école">
    <article>
      <nom>Classe passerelle</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Petite section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Moyenne section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Grande section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Cantine</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>TAP</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Garderie</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Projet école</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Horaires et emplois du temps">
    <article>
      <nom>Horaires et emplois du temps</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Inscriptions">
    <article>
      <nom>Inscriptions</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Conseils d'école">
    <article>
      <nom>2015</nom>
      <element balise="Fichier">conseil1.pdf</element>
    </article>
    <article>
      <nom>2016</nom>
      <element balise="Fichier">conseil2.pdf</element>
    </article>
    <article>
      <nom>2017</nom>
      <element balise="Fichier">conseil3.pdf</element>
    </article>
    <article>
      <nom>Archives</nom>
      <element balise="Fichier">conseil4.pdf</element>
    </article>
  </menu>
  <menu nom_menu="Contact">
    <article>
      <nom>Contact</nom>
      <element balise="Lien">http://www.google.com</element>
    </article>
  </menu>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-03-05_13-36-36.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="Accueil">
    <article>
      <nom>Accueil</nom>
      <element balise="Paragraphe">Nisi mihi Phaedrum, inquam, tu mentitum aut Zenonem putas, quorum utrumque audivi, cum mihi nihil sane praeter sedulitatem probarent, omnes mihi Epicuri sententiae satis notae sunt. atque eos, quos nominavi, cum Attico nostro frequenter audivi, cum miraretur ille quidem utrumque, Phaedrum autem etiam amaret, cotidieque inter nos ea, quae audiebamus, conferebamus, neque erat umquam controversia, quid ego intellegerem, sed quid probarem.</element>
    </article>
  </menu>
  <menu nom_menu="Présentation de l'école">
    <article>
      <nom>Classe passerelle</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Petite section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Moyenne section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Grande section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Cantine</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Horaires et emplois du temps">
    <article>
      <nom>Horaires et emplois du temps</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Inscriptions">
    <article>
      <nom>Inscriptions</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Conseils d'école">
    <article>
      <nom>2015</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>2016</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>2017</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>Archives</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
  </menu>
  <menu nom_menu="Contact">
    <article>
      <nom>Contact</nom>
      <element balise="Lien">http://www.google.com</element>
    </article>
  </menu>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-03-12_14-14-23.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="Présentation de l'école">
    <article>
      <nom>Nouvel article</nom>
    </article>
    <article>
      <nom>Nouvel article</nom>
    </article>
    <article>
      <nom>Grande section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Cantine</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>TAP</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Garderie</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Projet école</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-02-28_22-41-36.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="Accueiluu">
    <article>
      <nom>Accueiluu</nom>
    </article>
  </menu>
  <menu nom_menu="Cantine">
    <article>
      <nom>Cantine</nom>
      <element balise="Paragraphe">Article en cours de r√©daction</element>
    </article>
  </menu>
  <menu nom_menu="Archives">
    <article>
      <nom>Archives</nom>
      <element balise="Lien">../donnees/pdf/conseil.pdf</element>
    </article>
  </menu>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-03-07_22-59-01.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="Accueil">
    <article>
      <nom>Accueil</nom>
      <element balise="Carrousel"></element>
      <element balise="Paragraphe">Primi igitur omnium statuuntur Epigonus et Eusebius ob nominum gentilitatem oppressi. praediximus enim Montium sub ipso vivendi termino his vocabulis appellatos fabricarum culpasse tribunos ut adminicula futurae molitioni pollicitos.</element>
    </article>
  </menu>
  <menu nom_menu="Présentation de l'école">
    <article>
      <nom>Classe passerelle</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Petite section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Moyenne section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Grande section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Cantine</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Horaires et emplois du temps">
    <article>
      <nom>Horaires et emplois du temps</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Inscriptions">
    <article>
      <nom>Inscriptions</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Conseils d'école">
    <article>
      <nom>2015</nom>
      <element balise="Fichier">_fichier_defaut.pdf</element>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>2016</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>2017</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>Archives</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
  </menu>
  <menu nom_menu="Contact">
    <article>
      <nom>Contact</nom>
      <element balise="Lien">http://www.google.com</element>
    </article>
  </menu>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-03-10_15-41-51.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="Conseils d'Ã©cole">
    <article>
      <nom>2015</nom>
      <element balise="Fichier">conseil1.pdf</element>
    </article>
    <article>
      <nom>2016</nom>
      <element balise="Fichier">conseil2.pdf</element>
    </article>
    <article>
      <nom>2017</nom>
      <element balise="Fichier">conseil3.pdf</element>
    </article>
    <article>
      <nom>Archives</nom>
      <element balise="Fichier">conseil4.pdf</element>
    </article>
  </menu>
  <menu nom_menu="Contact">
    <article>
      <nom>Contact</nom>
      <element balise="Lien">http://www.google.com</element>
    </article>
  </menu>
</barre_menu>
