=== wilfalken/nathmorvan/donnees/dtd/articles.dtd
<!ELEMENT barre_menu (menu*)>
<!ELEMENT menu (article*)>
      <!ATTLIST menu
      	nom_menu CDATA #REQUIRED
      	>
<!ELEMENT article (nom, element*)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT element (#PCDATA)>
      <!ATTLIST element
      	balise CDATA #REQUIRED
      	>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-02-28_23-04-47.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="Accueilgg">
    <article>
      <nom>Accueilgg</nom>
    </article>
  </menu>
  <menu nom_menu="Horaires et emplois du temps">
    <article>
      <nom>Horaires et emplois du temps</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Inscriptions">
    <article>
      <nom>Inscriptions</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Contact">
    <article>
      <nom>Contact</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-03-10_15-46-20.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="Inscriptions">
    <article>
      <nom>Inscriptions</nom>
      <element balise="Paragraphe">Article en cours de r√©daction</element>
    </article>
  </menu>
  <menu nom_menu="Contact">
    <article>
      <nom>Contact</nom>
      <element balise="Lien">http://www.google.com</element>
    </article>
  </menu>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-03-07_22-56-01.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="Accueil">
    <article>
      <nom>Accueil</nom>
      <element balise="Carrousel"></element>
      <element balise="Sous-titre">Olim</element>
      <element balise="Paragraphe">Et olim licet otiosae sint tribus pacataeque centuriae et nulla suffragiorum certamina set Pompiliani redierit securitas temporis, per omnes tamen quotquot sunt partes terrarum, ut domina suscipitur et regina et ubique patrum reverenda cum auctoritate canities populique Romani nomen circumspectum et verecundum.</element>
      <element balise="Paragraphe">Quanta autem vis amicitiae sit, ex hoc intellegi maxime potest, quod ex infinita societate generis humani, quam conciliavit ipsa natura, ita contracta res est et adducta in angustum ut omnis caritas aut inter duos aut inter paucos iungeretur.</element>
      <element balise="Paragraphe">Primi igitur omnium statuuntur Epigonus et Eusebius ob nominum gentilitatem oppressi. praediximus enim Montium sub ipso vivendi termino his vocabulis appellatos fabricarum culpasse tribunos ut adminicula futurae molitioni pollicitos.</element>
    </article>
  </menu>
  <menu nom_menu="Présentation de l'école">
    <article>
      <nom>Classe passerelle</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Petite section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Moyenne section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Grande section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Cantine</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Horaires et emplois du temps">
    <article>
      <nom>Horaires et emplois du temps</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Inscriptions">
    <article>
      <nom>Inscriptions</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Conseils d'école">
    <article>
      <nom>2015</nom>
      <element balise="Fichier">_fichier_defaut.pdf</element>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>2016</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>2017</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>Archives</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
  </menu>
  <menu nom_menu="Contact">
    <article>
      <nom>Contact</nom>
      <element balise="Lien">http://www.google.com</element>
    </article>
  </menu>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-05-15_16-31-00.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="Inscriptions">
    <article>
      <nom>Inscriptions</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Horaires et emplois du temps">
    <article>
      <nom>dfe</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>feee</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Conseils d'école">
    <article>
      <nom>2014</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>2015</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>2015bis</nom>
      <element balise="Paragraphe">2015 bis</element>
    </article>
    <article>
      <nom>2016</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>2017</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
    <article>
      <nom>Archives</nom>
      <element balise="Fichier">conseil.pdf</element>
    </article>
  </menu>
  <menu nom_menu="Contact">
    <article>
      <nom>Contact</nom>
      <element balise="Paragraphe">Paragraphe en cours de modificationrt</element>
      <element balise="Lien">http://www.google.fr</element>
    </article>
  </menu>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-03-10_15-37-46.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="Présentation de l'école">
    <article>
      <nom>Classe passerelle</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Petite section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Moyenne section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Grande section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Cantine</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>TAP</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Garderie</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Projet école</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Conseils d'école">
    <article>
      <nom>2015</nom>
      <element balise="Fichier">conseil1.pdf</element>
    </article>
    <article>
      <nom>2016</nom>
      <element balise="Fichier">conseil2.pdf</element>
    </article>
    <article>
      <nom>2017</nom>
      <element balise="Fichier">conseil3.pdf</element>
    </article>
    <article>
      <nom>Archives</nom>
      <element balise="Fichier">conseil4.pdf</element>
    </article>
  </menu>
  <menu nom_menu="PrÃ©sentation de l'Ã©cole"/>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-03-12_14-41-23.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="Présentation de l'école">
    <article>
      <nom>a</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>ppp</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Nouvel article</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Cantine</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>TAP</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Garderie</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Projet école</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Horaires et emplois du tempseee">
    <article>
      <nom>Horaires et emplois du tempseee</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-03-16_21-22-49.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="frr">
    <article>
      <nom>frr</nom>
      <element balise="Paragraphe">Article en nnnhhaction</element>
    </article>
  </menu>
  <menu nom_menu="Horaires et emploi">
    <article>
      <nom>Horaires et emploi</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>o u</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>iuy</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>ytrt</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Horaires et emploi">
    <article>
      <nom>Horaires et emploi</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>o u</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>iuy</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>ytrt</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Conseils d'école">
    <article>
      <nom>2015</nom>
      <element balise="Fichier">conseil1.pdf</element>
    </article>
    <article>
      <nom>2016</nom>
      <element balise="Fichier">conseil2.pdf</element>
    </article>
    <article>
      <nom>2017</nom>
      <element balise="Fichier">conseil3.pdf</element>
    </article>
    <article>
      <nom>Archives</nom>
      <element balise="Fichier">conseil4.pdf</element>
    </article>
  </menu>
  <menu nom_menu="Inscriptions">
    <article>
      <nom>Inscriptions</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
</barre_menu>

=== wilfalken/nathmorvan/donnees/xml/autoback/articles_2017-03-12_14-59-26.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE barre_menu SYSTEM "../donnes/dtd/articles.dtd">
<barre_menu>
  <menu nom_menu="Accueil">
    <article>
      <nom>er</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>z"'r</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>c</nom>
    </article>
  </menu>
  <menu nom_menu="Présentation de l'école">
    <article>
      <nom>Classe passerelle</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Petite section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Moyenne section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Grande section</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Cantine</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>TAP</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Garderie</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
    <article>
      <nom>Projet école</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Horaires et emplois du temps">
    <article>
      <nom>Horaires et emplois du temps</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Inscriptions">
    <article>
      <nom>Inscriptions</nom>
      <element balise="Paragraphe">Article en cours de rédaction</element>
    </article>
  </menu>
  <menu nom_menu="Conseils d'école">
    <article>
      <nom>2015</nom>
      <element balise="Fichier">conseil1.pdf</element>
    </article>
    <article>
      <nom>2016</nom>
      <element balise="Fichier">conseil2.pdf</element>
    </article>
    <article>
      <nom>2017</nom>
      <element balise="Fichier">conseil3.pdf</element>
    </article>
    <article>
      <nom>Archives</nom>
      <element balise="Fichier">conseil4.pdf</element>
    </article>
  </menu>
  <menu nom_menu="Contact">
    <article>
      <nom>Contact</nom>
      <element balise="Lien">http://www.google.com</element>
    </article>
  </menu>
</barre_menu>
